# Configuração
@baseURL = http://127.0.0.1:3000
@trainerName = felipedie
@pocketName = padrao

### lista todos os bolsos do treinador
POST {{baseURL}}/pocket/list
Content-Type: application/json

{
    "trainerName": "felipedie"
}

### lista todos os pokemons no bolso do treinador
GET {{baseURL}}/pocket/content/{{trainerName}}/{{pocketName}}
Accept: application/json

### Insere um pokemon em um dos espaços no bolso do treinador
POST {{baseURL}}/pocket/add
Content-Type: application/json

{
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "pokemonName": "pikachu"
}

### Remove um pokemon em um dos espaços no bolso do treinador
POST {{baseURL}}/pocket/del
Content-Type: application/json

{
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "slotNumber": 3
}