# Configuração
@baseURL = http://127.0.0.1:3000
@trainerName = felipedie
@pocketName = padrao
@slotNumber = 1

### lista todos os bolsos do treinador
GET {{baseURL}}/pocket/list/{{trainerName}}
Accept: application/json

### lista o numero de slots nos bolsos do treinador
GET {{baseURL}}/pocket/slots/{{trainerName}}/{{pocketName}}
Accept: application/json

### lista a config dos movimentos do pokemon
GET {{baseURL}}/pocket/moves/{{trainerName}}/{{pocketName}}/{{slotNumber}}
Accept: application/json

### lista todos os pokemons no bolso do treinador
GET {{baseURL}}/pocket/content/felipedie/{{pocketName}}
Accept: application/json

### lista todos os pokemons no bolso do treinador
GET {{baseURL}}/pocket/content/machine/{{pocketName}}
Accept: application/json

### move um pokemon para outro bolso do treinador
PUT {{baseURL}}/pocket/pokemon/move
Content-Type: application/json

{
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "destinationPocket": "laboratorio",
    "slotNumber": 1
}

### delete uma habilidade do pokemon q subiu de nível
PUT {{baseURL}}/pocket/moves/rm
Content-Type: application/json

{
    "moveName": "growl",
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "slotNumber": 1
}

### Insere um pokemon em um dos espaços no bolso do treinador
POST {{baseURL}}/pocket/pokemon/add
Content-Type: application/json

{
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "pokemonName": "pikachu"
}

### Remove um pokemon em um dos espaços no bolso do treinador
POST {{baseURL}}/pocket/pokemon/del
Content-Type: application/json

{
    "trainerName": "felipedie",
    "pocketName": "padrao",
    "slotNumber": 3
}